apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: vote-github
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    -http:
      paths:
      - backend:
          serviceName: azure-vote-front
          servicePort: 80
        path: /